#### correlation using spearmans

# Spearman's correlation between age and waiting time
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.0, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.1.to.4, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.5.to.9, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.10.to.14, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.15, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.16, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.17, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.18, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.19, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.20.to.24, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.25.to.29, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.30.to.34, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.35.to.39, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.40.to.44, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.45.to.49, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.50.to.54, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.55.to.59, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.60.to.64, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.65.to.69, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.70.to.74, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.75.to.79, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.80.to.84, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.85.to.89, method = "spearman")
cor.test(a_e_data$Attendances.4.hours.or.less, a_e_data$age.over.90, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.0, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.1.to.4, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.5.to.9, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.10.to.14, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.15, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.16, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.17, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.18, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.19, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.20.to.24, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.25.to.29, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.30.to.34, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.35.to.39, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.40.to.44, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.45.to.49, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.50.to.54, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.55.to.59, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.60.to.64, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.65.to.69, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.70.to.74, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.75.to.79, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.80.to.84, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.85.to.89, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$age.over.90, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$UnknownAge, method = "spearman")

# Spearman's correlation between gender and waiting time
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Female, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Male, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Indeterminate, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$UnknownGender, method = "spearman")

# Spearman's correlation between ethnicity and waiting time
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$African..Black.or.Black.British., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Any.other.Asian.background, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Any.other.Black.background, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Any.other.ethnic.group, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Any.other.White.background, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Bangladeshi..Asian.or.Asian.British., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Caribbean..Black.or.Black.British., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Chinese..other.ethnic.group., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Indian..Asian.or.Asian.British., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Pakistani..Asian.or.Asian.British., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Not.stated, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$White.Irish..White., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$White.and.Asian..Mixed., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$White.and.Black.African..Mixed., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$White.British..White., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$White.and.Black.Caribbean..Mixed., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$UnknownEthnicity, method = "spearman")

# Spearman's correlation between Deprivation level and waiting time
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Least.deprived.10., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Less.deprived.10.20., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Less.deprived.20.30., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Less.deprived.30.40., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Less.deprived.40.50., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$More.deprived.40.50., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$More.deprived.30.40., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$More.deprived.20.30., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$More.deprived.10.20., method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Most.deprived.10., method = "spearman")

# Spearman's correlation between department type and waiting time
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Type.1.Consultant.led.A.E, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Type.2.Single.specialty.A.E, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Types.3...4.Minor.Injury.or.Walk.in.units, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$UnknownDepttype, method = "spearman")

##
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Total.emergency.workforce, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Total.available.beds, method = "spearman")
cor.test(a_e_data$Attendances.over.4.hours, a_e_data$Total.occupied.beds, method = "spearman")
